import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LanguageToggle from "../components/languageToggle/languageToggle";
import ScrollUpButton from "../components/scrollUpButton/scrollUpButton";
import ThemeToggle from "../components/themeToggle/themeToggle";
import { LanguageProvider } from "../contexts/LanguageContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kevin's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head />
      <body className="min-h-full flex flex-col">
        <LanguageProvider>
          <ThemeToggle />
          <LanguageToggle />
          {children}
          <ScrollUpButton />
        </LanguageProvider>
      </body>
    </html>
  );
}
